- name: Configure AI server baseline and AI stack
  hosts: gex0
  remote_user: devops
  become: true
  gather_facts: true
  vars:
    ansible_become_password: "{{ vault_all.ansible_become_password }}"

  roles:
    - role: harden
      tags: harden
    - role: docker_engine
      tags: docker_engine
    - role: nginx
      tags: nginx
    - role: certbot_tls
      tags: certbot_tls
    - role: ai_rig
      tags: ai_rig
