- name: Deploy Lantern runtime package
  hosts: gex0
  become: true
  gather_facts: false
  tags:
    - lantern_runtime
  roles:
    - role: lantern_deploy
      tags: lantern_runtime

- name: Deploy Lantern app bundle
  hosts: gex0
  become: true
  gather_facts: false
  tags:
    - lantern_app
  roles:
    - role: lantern_app_deploy
      tags: lantern_app
