- name: Deploy Lantern runtime package
  hosts: gex0
  become: true
  gather_facts: false
  tags:
    - lantern_runtime
  #pre_tasks:
  #  - name: Initialize Lantern runtime target filesystem
  #    vars:
        lantern_target_init_user: lantern
        lantern_target_init_group: lantern
        lantern_target_init_directories:
          - path: /var/log/lantern
            owner: lantern
            group: lantern
            mode: "0755"
  roles:
    - role: lantern_deploy
      tags: lantern_runtime

- name: Deploy Lantern app bundle
  hosts: gex0
  become: true
  gather_facts: false
  tags:
    - lantern_app
  pre_tasks:
    - name: Initialize Lantern app target filesystem
      vars:
        lantern_target_init_user: lantern
        lantern_target_init_group: lantern
        lantern_target_init_directories:
          - path: /srv/lantern
            owner: lantern
            group: lantern
            mode: "0755"
          - path: /srv/lantern/apps
            owner: lantern
            group: lantern
            mode: "0755"
          - path: /var/log/lantern
            owner: lantern
            group: lantern
            mode: "0755"
  roles:
    - role: lantern_app_deploy
      tags: lantern_app
