- name: Deploy Pharos runtime package
  hosts: web0
  become: true
  gather_facts: false
  tags:
    - pharos_runtime
  roles:
    - role: pharos_deploy
      tags: pharos_runtime

- name: Deploy Pharos app bundle
  hosts: web0
  become: true
  gather_facts: false
  tags:
    - pharos_app
  vars:
    app_id: ucal
    clean_app: false
    # Update repositories on the controller before building when true
    update_repo: false
  roles:
    - role: pharos_app_deploy
      tags:
        - pharos_app
