- hosts: all
  #  strategy: free
  tags:
    - kymstr
  pre_tasks:
  - name: Info
    debug:
      msg:
        - 'ip: {{ansible_host}}'
        - 'name: {{host_name}}'
        - 'os: {{ansible_lsb.description}}'

  roles:
    - keymaster