- name: Configure repo server baseline and Forgejo
  hosts: repo0
  tags:
    - repo_server
  roles:
    - role: ubuntu_pro_fips
      tags: ubuntu_pro_fips
    - role: harden
      tags: harden
    - role: docker_engine
      tags: docker_engine
    - role: nginx
      tags: nginx
    - role: certbot_tls
      tags: certbot_tls
    - role: forgejo_container
      tags: forgejo
    - role: forgejo_pull
      tags: forgejo_pull

- name: Configure AI server baseline and AI stack
  hosts: gex0
  tags:
    - ai_server
  roles:
    - role: harden
      tags: harden
    - role: docker_engine
      tags: docker_engine
    - role: nginx
      tags: nginx
    - role: certbot_tls
      tags: certbot_tls
    - role: ai_rig
      tags: ai_rig
    - role: lantern
      tags: lantern
