- name: Install ufw package
  apt:
    name: ufw
    state: present
    update_cache: true

- name: Allow SSH through UFW
  community.general.ufw:
    rule: allow
    port: "22"
    proto: tcp

- name: Allow HTTP and HTTPS through UFW
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "80"
    - "443"

- name: Install certbot packages
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present
    update_cache: true
