- name: Gather installed package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Disable UFW if installed
  community.general.ufw:
    state: disabled
  when: "'ufw' in ansible_facts.packages"

- name: Remove UFW package
  ansible.builtin.apt:
    name: ufw
    state: absent
    purge: true
    autoremove: true
  when: "'ufw' in ansible_facts.packages"

- name: Install certbot packages
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present
    update_cache: true
