# env
local_ip: 127.0.0.1
autobuild: true
unattended_upgrades: true
domain: 'llight.io'
admin_user: "devops"
admin_email: "{{ admin_user }}@{{ domain }}"

ansible_python_interpreter: auto_silent

# keys
auth_user: viewer
auth_pass: "{{vault_all.auth_pass}}"
ansible_become_password: "{{vault_all.ansible_become_password}}"

# Ports
email_port: 587
netcat_port: 1337
postgres_port: 5432
redis_port: 6379
sonarqube_port: 9023

# ssl
ssl_dir: "/etc/ssl"
ssl_sites_dir: "{{ssl_dir}}/epetype"

# certbot
certbot_admin_email: "{{admin_email}}"
certbot_domain_type: "single"

# gcp
gcp_org_id: "{{vault_all.gcp_llight.org_id}}"
gcp_proj_id: "{{vault_all.gcp_llight.proj_id}}"
gcp_region: "us-west1"
gcp_zone: "us-west1-a"

#sonarqube
monitor_ip: "{{hostvars['monitor_prd']['ansible_host']}}"
sonardb:
  name: "sonarqube"
  user: "{{vault_all.sonardb.user}}"
  pass: "{{vault_all.sonardb.pass}}"
