# tailscale policy overrides
tailscale_policy_groups:
  group:ll-admins:
    - "helios23@gmail.com"
  group:ll-users:
    - "helios23@gmail.com"

tailscale_policy_tag_owners:
  tag:ll:
    - "group:ll-admins"

tailscale_policy_grants:
  - src:
      - "group:ll-admins"
      - "group:ll-users"
    dst:
      - "tag:ll"
    ip:
      - "tcp:22"

tailscale_policy_ssh:
  - action: "accept"
    src:
      - "group:ll-admins"
    dst:
      - "tag:ll"
    users:
      - "devops"
  - action: "accept"
    src:
      - "group:ll-users"
    dst:
      - "tag:ll"
    users:
      - "rp"
