luks_nbde_packages:
  - clevis
  - clevis-initramfs
  - clevis-luks
  - clevis-systemd
  - cryptsetup-initramfs

luks_nbde_luks_device: ""
luks_nbde_clevis_pin: "tang"
luks_nbde_clevis_config: {}

luks_nbde_require_ubuntu_jammy: true
luks_nbde_require_fips_compatible_pbkdf2: true
luks_nbde_manage_recovery_pbkdf2_slot: false

luks_nbde_existing_unlock_secret: ""
luks_nbde_recovery_passphrase: ""

luks_nbde_enable_late_boot_unlock: false
