#user auth
ssh_user: "devops"
key_domain: "{{ org_name }}.{{ org_suffix }}"
org_name: "epytype"
org_suffix: "org"

#dirs
key_dir: "{{ playbook_dir }}/keys"
ssl_dir: "/etc/ssl/{{ org_name }}"
ssh_dir: "{{ key_dir }}/ssh"
csr_dir: "{{ key_dir }}/csr"
priv_dir: "{{ key_dir }}/priv"
site_dir: "{{ key_dir }}/site"

# Site certs
sites:
  - "demo.{{ key_domain }}"

key_email: "support@{{ key_domain }}"
key_org_name: "Epytype"
key_org_unit: "IT"
key_country: "US"
key_state: "Dellaware"
key_city: "Wilmington"

#CSR_LIST
csr_list:
  - name: "{{ key_domain }}"
