- name: restart docker
  systemd:
    name: docker
    state: restarted

- name: Reload nginx
  service:
    name: nginx
    state: reloaded

- name: restart open-webui
  systemd:
    name: open-webui.service
    state: restarted
