- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 0

- name: Reboot for FIPS kernel
  reboot:
    msg: "Reboot initiated by Ansible after Ubuntu Pro FIPS enablement"
    connect_timeout: 20
    reboot_timeout: 1800
    post_reboot_delay: 20
