# Ubuntu Pro
ubuntu_pro_enable: true
ubuntu_pro_token: "{{ vault_all.ubuntu_pro.repo_token }}"
ubuntu_pro_fips_service: "fips-updates"
ubuntu_pro_usg_enable: true
ubuntu_pro_usg_profile: "cis_level1_server"
ubuntu_pro_usg_run_fix: true
ubuntu_pro_usg_run_audit: true
ubuntu_pro_preserve_access: true
ubuntu_pro_access_user: "devops"
ubuntu_pro_access_public_key_path: "{{ playbook_dir }}/keys/ssh/devops.epytype.org.pub"
ubuntu_pro_access_public_key_paths:
  - "{{ playbook_dir }}/keys/ssh/devops.epytype.org.fips_rsa.pub"
  - "{{ ubuntu_pro_access_public_key_path }}"
ubuntu_pro_access_password: "{{ vault_all.ansible_become_password }}"

# Forgejo
allowed_ssh_users:
  - "devops"
sshd_password_auth: "yes"
sshd_additional_protected_ports:
  - 2222
forgejo_fail2ban_enabled: true
forgejo_http_port: 3000
forgejo_ssh_port: 2222
forgejo_postgres_password: "{{ vault_all.forgejo.postgres_password }}"
# mail
forgejo_mailer_enabled: true
forgejo_mailer_from: "devops@epytype.org"
forgejo_mailer_protocol: "smtp+starttls"
forgejo_mailer_smtp_port: 587
forgejo_mailer_smtp_addr: "smtp.gmail.com"
forgejo_mailer_user: "{{ vault_all.forgejo.smtp_user }}"
forgejo_mailer_passwd: "{{ vault_all.forgejo.smtp_password }}"
forgejo_mailer_enable_notify_mail: true
forgejo_mailer_enable_helo: true
forgejo_mailer_helo_hostname: "repo.epytype.org"
forgejo_mailer_envelope_from: "{{ vault_all.forgejo.smtp_user }}"
